### ISSUE TITLE
Site does not work on mobile

### ISSUE THREAD

**Issue by w3bdesign** [rperry99/splash-page#1]
The site does not work on mobile.

The main reason for this seems to be the elements that have been absolutely positioned.

I highly recommend that you recreate the project using CSS Grid / Flex as it makes it easier to make the site responsive.

**Comment by rperry99** [comment]
Yeah, I know this isn't responsive. This was from a JS course I was working through and they just wanted to show how to take design from Figma and recreate it in code. I didn't intend for the projects from the course to be part of a portfolio or anything.

**Comment by w3bdesign** [comment]
No problem, I am closing this.
